import type { Metadata } from "next";
import "../tool-pages.css";
import { buildPageMetadata } from "../site-metadata";

export const metadata:Metadata=buildPageMetadata({
  title:"Privacy Policy | AI Body Fat Calculator",
  description:"How AI Body Fat Calculator processes uploaded photos, stores device-level scan counts, and uses Alibaba Cloud Model Studio for AI analysis.",
  path:"/privacy",
});

export default function Privacy(){return <div className="tool-page"><header className="tool-nav"><a href="/">BF · AI Body Fat Calculator</a></header><main className="tool-main legal-page"><div className="tool-eyebrow">LAST UPDATED AUGUST 26, 2026</div><h1>Privacy Policy</h1><p className="tool-lede">We designed AI Body Fat Calculator to analyze your photo without building a photo library.</p><h2>Photo processing</h2><p>Your uploaded image is sent to Alibaba Cloud Model Studio solely to generate the requested analysis. The application does not write your photo to its own database or persistent file storage.</p><h2>Optional baseline data</h2><p>If you choose “Save this baseline,” AI Body Fat Calculator stores only the numeric analysis result and date in your browser. The photo is not included. You can remove the baseline through your browser settings or replace it with a later result.</p><h2>Device data</h2><p>Your browser stores the date and number of free analyses used to enforce the three-per-day device limit. You can remove this data through your browser settings.</p><h2>Third-party processing and location</h2><p>Alibaba Cloud processes the image and prompt to provide the analysis API service in its China (Beijing) region. AI Body Fat Calculator does not control Alibaba Cloud&apos;s service-level logs or retention. Those practices depend on the configured Alibaba Cloud service and account controls. Do not upload a photo if you do not consent to this processing location.</p><h2>Model training and deletion requests</h2><p>AI Body Fat Calculator does not use uploaded photos to train its own model. Questions about processing, retention, or deletion requests may be sent to hello@aibodyfatcalculator.com. We will handle requests within the controls available to the service.</p><h2>Contact</h2><p>Questions may be sent to hello@aibodyfatcalculator.com.</p><a className="back-cta" href="/">Return to calculator</a></main></div>}
