import type {Metadata} from "next";
import FfmiCalculator from "./FfmiCalculator";
import "../tool-pages.css";
import "./ffmi.css";

const canonical="https://aibodyfatcalculator.com/ffmi-calculator";
export const metadata:Metadata={title:"FFMI Calculator - Fat Free Mass Index (Normalized)",description:"Free FFMI calculator: measure your fat free mass index from height, weight and body fat %. Includes normalized FFMI and interpretation charts for men and women.",alternates:{canonical},openGraph:{title:"FFMI Calculator - Fat Free Mass Index (Normalized)",description:"Calculate fat-free mass, FFMI, normalized FFMI, and interpret the result responsibly.",url:canonical,siteName:"BodyLens",type:"website"}};

const faqs=[
  ["What is a good FFMI score?","FFMI varies by sex, age, population, sport, and body-fat measurement method. In common fitness references, values around 21–23 for men are often described as excellent, but no single range applies to everyone."],
  ["What is the natural FFMI limit?","There is no definitive individual natural limit. A preliminary 1995 study found normalized FFMI values up to 25 among its male non-user sample. FFMI alone cannot establish whether someone uses performance-enhancing substances."],
  ["How is normalized FFMI different from FFMI?","Normalized FFMI adjusts for height using FFMI + 6.3 × (1.80 − height in meters), allowing comparison at a reference height of 1.80 meters."],
  ["Does FFMI require body fat percentage?","Yes. This calculator uses body-fat percentage to estimate fat-free mass. If you do not know yours, you can use our AI body fat calculator for a directional photo estimate."],
] as const;
const menRows=[["17–18","10–18%","Lower muscularity"],["18–20","20–27%","Typical range"],["19–21","25–40%","Higher fat mass"],["20–21","10–18%","Athletic / intermediate"],["22–23","6–12%","Advanced muscularity"],["24–25","8–20%","Very high muscularity"]];
const womenRows=[["14–15","20–25%","Lower muscularity"],["14–17","22–35%","Typical range"],["15–18","30–45%","Higher fat mass"],["16–17","18–25%","Athletic / intermediate"],["18–20","15–22%","Advanced muscularity"],["19–21","15–30%","Very high muscularity"]];
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
const appSchema={"@context":"https://schema.org","@type":"SoftwareApplication",name:"BodyLens FFMI Calculator",alternateName:"FFMI Calculator",applicationCategory:"HealthApplication",operatingSystem:"Web",url:canonical,brand:{"@type":"Brand",name:"BodyLens"},publisher:{"@id":"https://aibodyfatcalculator.com/#organization"},isAccessibleForFree:true,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}};
const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://aibodyfatcalculator.com/"},{"@type":"ListItem",position:2,name:"FFMI Calculator",item:canonical}]};

export default function FfmiPage(){return <div className="tool-page"><header className="tool-nav"><a href="/">BF · BodyLens</a><div><a href="/ffmi-calculator">FFMI</a><a href="/army-body-fat-calculator">Army</a><a href="/tdee-calculator">TDEE</a><a href="/bmi-calculator">BMI</a></div></header><main className="tool-main ffmi-page">
  <div className="tool-eyebrow">FREE BODY COMPOSITION TOOL</div><h1>FFMI Calculator</h1><p className="ffmi-subtitle">Determine your Fat Free Mass Index</p><p className="tool-lede">Enter height, weight, and body-fat percentage to calculate fat-free mass, standard FFMI, and normalized FFMI in metric or US units.</p>
  <FfmiCalculator/>
  <section className="content-block"><h2>What is FFMI?</h2><p>FFMI means Fat-Free Mass Index. It compares fat-free body mass with height, helping distinguish how much of total weight comes from lean tissue rather than fat. This makes a fat free mass index more informative than BMI for many strength athletes and regular gym users.</p><p>An FFMI calculator still depends on an estimate of body-fat percentage. If that input changes, fat-free mass and FFMI change too. Use the same measurement method when tracking progress over time.</p></section>
  <section className="content-block"><h2>FFMI Formula</h2><div className="formula-grid"><article><span>STANDARD FFMI</span><strong>fat-free mass (kg) ÷ height² (m)</strong><p>Fat-free mass = body weight × (1 − body-fat percentage ÷ 100).</p></article><article><span>NORMALIZED FFMI</span><strong>FFMI + 6.3 × (1.80 − height)</strong><p>The Kouri correction normalizes FFMI to a reference height of 1.80 meters.</p></article></div></section>
  <section className="content-block"><h2>FFMI Interpretation</h2><p>These overlapping fitness-oriented reference descriptions are not clinical classifications. Body-fat range affects how the same FFMI may look, and population-specific research can produce different distributions.</p><div className="interpret-grid"><InterpretTable title="Men’s FFMI reference" rows={menRows}/><InterpretTable title="Women’s FFMI reference" rows={womenRows}/></div><p className="evidence-note"><strong>About the frequently quoted “FFMI 25 limit”:</strong> a 1995 study of 157 male athletes found normalized FFMI values up to 25 in its non-user sample and described the findings as preliminary. A study of 266 female collegiate athletes reported values ranging from 13.3 to 25.5. A score cannot prove or disprove drug use.</p></section>
  <section className="content-block"><h2>How to Use This FFMI Calculator</h2><ol className="steps-list"><li>Choose metric or US units.</li><li>Enter your current height and body weight.</li><li>Enter your best available body-fat percentage estimate.</li><li>Read fat-free mass, fat mass, FFMI, and normalized FFMI.</li><li>Repeat with the same body-fat measurement method to track trends consistently.</li></ol></section>
  <section className="content-block source-list"><h2>Research Sources</h2><ul><li><a href="https://pubmed.ncbi.nlm.nih.gov/7496846/" rel="noopener noreferrer">Kouri et al. (1995): FFMI in users and nonusers of anabolic-androgenic steroids</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/30893018/" rel="noopener noreferrer">Blue et al. (2019): FFMI values for female collegiate athletes</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4684827/" rel="noopener noreferrer">NHANES III FFMI percentile research</a></li></ul></section>
  <section className="content-block ffmi-faq"><h2>FFMI Calculator FAQ</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  <section className="content-block"><h2>Related Body Composition Tools</h2><div className="related-ffmi"><a href="/"><span>PHOTO ESTIMATE</span><strong>AI Body Fat Calculator →</strong></a><a href="/tdee-calculator"><span>DAILY CALORIES</span><strong>TDEE Calculator →</strong></a><a href="/bmi-calculator"><span>WEIGHT INDEX</span><strong>BMI Calculator →</strong></a><a href="/body-fat-percentage-chart"><span>REFERENCE RANGES</span><strong>Body Fat Chart →</strong></a></div></section>
  <div className="ffmi-disclaimer"><strong>⚠ Disclaimer:</strong> This FFMI calculator provides an educational estimate only. It is not a medical device and is not intended to diagnose, treat, or prevent any condition. “Natural limit” interpretations are statistical references from published research, not definitive judgments about an individual. Consult a qualified professional for health decisions.</div>
  </main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(appSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/></div>}

function InterpretTable({title,rows}:{title:string;rows:string[][]}){return <article className="interpret-card"><h3>{title}</h3><div className="interpret-row head"><span>FFMI</span><span>Body fat</span><span>Context</span></div>{rows.map(row=><div className="interpret-row" key={row.join("-")}><b>{row[0]}</b><span>{row[1]}</span><span>{row[2]}</span></div>)}</article>}
