import type {Metadata} from "next";
import FfmiCalculator from "./FfmiCalculator";
import "../tool-pages.css";
import "./ffmi.css";
import { buildPageMetadata } from "../site-metadata";

const canonical="https://aibodyfatcalculator.com/ffmi-calculator";
export const metadata:Metadata=buildPageMetadata({title:"FFMI Calculator — Fat Free Mass Index (Normalized) | AI Body Fat Calculator",description:"Calculate fat-free mass, standard FFMI, and normalized FFMI from height, weight, and body fat percentage, with responsible interpretation ranges.",path:"/ffmi-calculator"});

const faqs=[
  ["What is a good FFMI score?","FFMI varies by sex, age, population, sport, and body-fat measurement method. In common fitness references, values around 21–23 for men are often described as excellent, but no single range applies to everyone."],
  ["What is the natural FFMI limit?","There is no definitive individual natural limit. A preliminary 1995 study found normalized FFMI values up to 25 among its male non-user sample. FFMI alone cannot establish whether someone uses performance-enhancing substances."],
  ["How is normalized FFMI different from FFMI?","Normalized FFMI adjusts for height using FFMI + 6.3 × (1.80 − height in meters), allowing comparison at a reference height of 1.80 meters."],
  ["Does FFMI require body fat percentage?","Yes. This calculator uses body-fat percentage to estimate fat-free mass. If you do not know yours, you can use our AI body fat calculator for a directional photo estimate."],
  ["Is this a fat free mass calculator too?","Yes. The calculator returns fat-free mass, fat mass, standard FFMI, and normalized FFMI from the same height, weight, and body-fat inputs."],
  ["Can women use this FFMI calculator?","Yes. Women can use the same FFMI formula, but interpretation should use women-specific context because typical lean-mass distributions differ from men's ranges."],
] as const;
const menRows=[["17–18","10–18%","Lower muscularity"],["18–20","20–27%","Typical range"],["19–21","25–40%","Higher fat mass"],["20–21","10–18%","Athletic / intermediate"],["22–23","6–12%","Advanced muscularity"],["24–25","8–20%","Very high muscularity"]];
const womenRows=[["14–15","20–25%","Lower muscularity"],["14–17","22–35%","Typical range"],["15–18","30–45%","Higher fat mass"],["16–17","18–25%","Athletic / intermediate"],["18–20","15–22%","Advanced muscularity"],["19–21","15–30%","Very high muscularity"]];
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
const appSchema={"@context":"https://schema.org","@type":"SoftwareApplication",name:"FFMI Calculator",alternateName:["Fat Free Mass Index Calculator","Fat Free Mass Calculator","Female FFMI Calculator"],applicationCategory:"HealthApplication",operatingSystem:"Web",url:canonical,brand:{"@type":"Brand",name:"AI Body Fat Calculator"},publisher:{"@id":"https://aibodyfatcalculator.com/#organization"},isAccessibleForFree:true,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}};
const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://aibodyfatcalculator.com/"},{"@type":"ListItem",position:2,name:"FFMI Calculator",item:canonical}]};

export default function FfmiPage(){return <div className="tool-page"><header className="tool-nav"><a href="/">BF · AI Body Fat Calculator</a><div><a href="/ffmi-calculator">FFMI</a><a href="/army-body-fat-calculator">Army</a><a href="/tdee-calculator">TDEE</a><a href="/bmi-calculator">BMI</a></div></header><main className="tool-main ffmi-page">
  <div className="tool-eyebrow">FREE BODY COMPOSITION TOOL</div><h1>FFMI Calculator</h1><p className="ffmi-subtitle">Determine your Fat Free Mass Index</p><p className="tool-lede">Enter height, weight, and body-fat percentage to calculate fat-free mass, standard FFMI, and normalized FFMI in metric or US units.</p>
  <FfmiCalculator/>
  <section className="content-block"><h2>What is FFMI?</h2><p>FFMI means Fat-Free Mass Index. It compares fat-free body mass with height, helping distinguish how much of total weight comes from lean tissue rather than fat. This makes a fat free mass index more informative than BMI for many strength athletes and regular gym users.</p><p>An FFMI calculator still depends on an estimate of body-fat percentage. If that input changes, fat-free mass and FFMI change too. Use the same measurement method when tracking progress over time.</p></section>
  <section className="content-block"><h2>FFMI Formula</h2><div className="formula-grid"><article><span>STANDARD FFMI</span><strong>fat-free mass (kg) ÷ height² (m)</strong><p>Fat-free mass = body weight × (1 − body-fat percentage ÷ 100).</p></article><article><span>NORMALIZED FFMI</span><strong>FFMI + 6.3 × (1.80 − height)</strong><p>The Kouri correction normalizes FFMI to a reference height of 1.80 meters.</p></article></div></section>
  <section className="content-block"><h2>Fat Free Mass Calculator</h2><p>This tool also works as a fat free mass calculator. Fat-free mass is everything in body weight that is not fat mass, including muscle, bone, organs, water, and connective tissue. To estimate it, multiply body weight by the non-fat portion of your body composition.</p><div className="formula-grid"><article><span>FAT-FREE MASS</span><strong>weight × (1 − body fat %)</strong><p>Example: 180 lb at 18% body fat has about 147.6 lb of fat-free mass.</p></article><article><span>FAT MASS</span><strong>weight × body fat %</strong><p>Example: 180 lb at 18% body fat has about 32.4 lb of fat mass.</p></article></div><p>Because fat-free mass depends on the body-fat input, do not compare results from different measurement methods too aggressively. A photo estimate, smart scale, caliper test, and DXA scan may all produce different body-fat inputs.</p></section>
  <section className="content-block"><h2>FFMI Chart</h2><p>An FFMI chart is best used as a broad fitness reference, not a clinical classification. The same FFMI can look different depending on body-fat percentage, height, limb length, and where muscle is distributed.</p><div className="chart-table ffmi-chart-table"><div className="chart-row"><span>FFMI RANGE</span><b>GENERAL CONTEXT</b><b>TRACKING NOTE</b></div>{[["Below 18","Lower lean mass for many men; may be normal for women or smaller frames","Use with sex-specific context"],["18-20","Common recreational range","Track strength and waist trend"],["20-22","Solid muscularity for many lifters","Good range for recomposition tracking"],["22-24","Advanced lean mass in many fitness contexts","Measurement accuracy matters more"],["24-25+","Very high muscularity","Use cautiously; not proof of enhancement"]].map(row=><div className="chart-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><b>{row[2]}</b></div>)}</div></section>
  <section className="content-block"><h2>FFMI Interpretation</h2><p>These overlapping fitness-oriented reference descriptions are not clinical classifications. Body-fat range affects how the same FFMI may look, and population-specific research can produce different distributions.</p><div className="interpret-grid"><InterpretTable title="Men’s FFMI reference" rows={menRows}/><InterpretTable title="Women’s FFMI reference" rows={womenRows}/></div><p className="evidence-note"><strong>About the frequently quoted “FFMI 25 limit”:</strong> a 1995 study of 157 male athletes found normalized FFMI values up to 25 in its non-user sample and described the findings as preliminary. A study of 266 female collegiate athletes reported values ranging from 13.3 to 25.5. A score cannot prove or disprove drug use.</p></section>
  <section className="content-block"><h2>FFMI Calculator Female Guide</h2><p>Women can use the same FFMI formula, but women-specific interpretation is important. Typical body-fat ranges, essential fat needs, and lean-mass distributions differ from men's ranges, so a female FFMI result should not be judged against male bodybuilding references.</p><p>The 2019 female collegiate athlete study cited below reported a wide range of FFMI values across sports. That is the useful lesson: sport, training age, body size, and measurement method matter. For most women, the best use of FFMI is to track whether lean mass is being preserved or gained while body fat changes.</p></section>
  <section className="content-block"><h2>How to Use This FFMI Calculator</h2><ol className="steps-list"><li>Choose metric or US units.</li><li>Enter your current height and body weight.</li><li>Enter your best available body-fat percentage estimate.</li><li>Read fat-free mass, fat mass, FFMI, and normalized FFMI.</li><li>Repeat with the same body-fat measurement method to track trends consistently.</li></ol></section>
  <section className="content-block source-list"><h2>Research Sources</h2><ul><li><a href="https://pubmed.ncbi.nlm.nih.gov/7496846/" rel="noopener noreferrer">Kouri et al. (1995): FFMI in users and nonusers of anabolic-androgenic steroids</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/30893018/" rel="noopener noreferrer">Blue et al. (2019): FFMI values for female collegiate athletes</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4684827/" rel="noopener noreferrer">NHANES III FFMI percentile research</a></li></ul></section>
  <section className="content-block ffmi-faq"><h2>FFMI Calculator FAQ</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  <section className="content-block"><h2>Related Body Composition Tools</h2><div className="related-ffmi"><a href="/"><span>PHOTO ESTIMATE</span><strong>AI Body Fat Calculator →</strong></a><a href="/ffmi-vs-bmi"><span>METRIC GUIDE</span><strong>FFMI vs BMI →</strong></a><a href="/how-to-measure-body-fat-at-home"><span>MEASUREMENT</span><strong>Measure Body Fat at Home →</strong></a><a href="/body-fat-percentage-chart"><span>REFERENCE RANGES</span><strong>Body Fat Chart →</strong></a></div></section>
  <div className="ffmi-disclaimer"><strong>⚠ Disclaimer:</strong> This FFMI calculator provides an educational estimate only. It is not a medical device and is not intended to diagnose, treat, or prevent any condition. “Natural limit” interpretations are statistical references from published research, not definitive judgments about an individual. Consult a qualified professional for health decisions.</div>
  </main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(appSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/></div>}

function InterpretTable({title,rows}:{title:string;rows:string[][]}){return <article className="interpret-card"><h3>{title}</h3><div className="interpret-row head"><span>FFMI</span><span>Body fat</span><span>Context</span></div>{rows.map(row=><div className="interpret-row" key={row.join("-")}><b>{row[0]}</b><span>{row[1]}</span><span>{row[2]}</span></div>)}</article>}
